feat: ["feat/*", "feature/*", "*/feat/*", "*/feature/*"]
fix: ["bugfix/*", "hotfix/*", "bug/*", "fix/*", "*/bugfix/*", "*/hotfix/*", "*/bug/*", "*/fix/*"]
design: ["design/*", "ui/*", "ux/*", "*/design/*", "*/ui/*", "*/ux/*"]
docs: ["docs/*", "doc/*", "*/docs/*", "*/doc/*"]
test: ["test/*", "tests/*", "*/test/*", "*/tests/*"]
perf: ["perf/*", "performance/*", "*/perf/*", "*/performance/*"]
refactor: ["refactor/*", "*/refactor/*"]
chore: ["chore/*", "*/chore/*"]
ci: ["ci/*", "*/ci/*"]
project management: ["project-management/*", "project/*", "*/project-management/*", "*/project/*"]
