name: Auto approve

on:
  pull_request_target:
  issue_comment:

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: LGTM Action
        uses: docker://jonyhy/lgtm-action:v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Auto approve for Dependabot
        if: github.actor == 'dependabot[bot]' && github.event_name == 'pull_request_target'
        uses: hmarr/auto-approve-action@v3
