name: Project Issue State Sync

on: 
  workflow_dispatch:
    # At minute 0 every 2 hours
    - cron: 0 0-23/2 * * *

jobs:
  issue-state-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync issue states
        uses: dasmerlon/project-issue-state-sync@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: yamyam263
          project_number: 3
          closed_stati: DONE
          open_stati: TODO,DOING,CODE REVIEW
